# .nosana-ci.yml
global:
  image: nosana/solana
  trigger:
    push:
      branches:
        - "*"

jobs:
  - name: build
    commands:
      - echo "building..."
      - mkdir dist
    artifacts:
      - name: dist
      - name: node_modules

  - name: test
    commands:
      - echo "testing..."
    resources:
      - name: dist

  - name: deploy
    commands:
      - echo "deploying..."
    resources:
      - name: dist